name: nss-pam-ldapd # check to see if it's available
version: git
summary: A fork of nss_ldap with some structural design improvements # 79 char long summary
description: |
  This is nss-pam-ldapd which provides a Name Service Switch (NSS, nsswitch) module that allows your LDAP server to provide user account, group, host name, alias, netgroup, and basically any other information that you would normally get from /etc flat files or NIS. It also provides a Pluggable Authentication Module (PAM) to do identity and authentication management with an LDAP server on unix systems. This is implemented using thin NSS and PAM modules which delegate to a dedicated service (nslcd) that queries the LDAP server with persistent connections, authentication, attribute translation, etc.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  nss-pam-ldapd:
    command: nss-pam-ldapd
    plugs:
      - home
      - network
      - network-bind
     
parts: 
  nss-pam-ldapd:
    source: https://arthurdejong.org/nss-pam-ldapd/release-0-9-10
    source-type: tar
    plugin: make
